### ISSUE TITLE
Spot check vote data

### ISSUE THREAD

**Issue by GrahamGoudeau** [Dtphelan1/arlington-ma-town-member-voting#13]
We should be sure that the voting data got cleaned/converted properly. We should all pick a fe random votes/town meeting members from the spreadsheets and make sure that the entries are correct in the data from the API.

**Comment by GrahamGoudeau** [comment]
- [x] Scott Lever, precinct 8, 2020-11-23, article 4, abstain
- [x] Robin Dratch, precinct 3, 2020-11-18, article 8, no data
- [x] Nancy Bloom, precinct 18, 2020-11-18, article 6, yes
- [x] John Leonard, precinct 17, 2020-12-02, article 25, yes verbally
- [x] Curtis Connors, precinct 20, 2020-11-16, article 3, yes

**Comment by Dtphelan1** [comment]
Looks pretty good so far.
