### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by GrahamGoudeau** [Dtphelan1/arlington-ma-town-member-voting#8]

**Comment by GrahamGoudeau** [comment]
# All About Vote Smart Arlington

Vote Smart Arlington is an effort to present Arlington, MA town member voting records in a novel and accessible way. Our site gives Arlington town residents the ability to select their precinct and view their town meeting members' voting history for all of 2020, which we hope can serve as an informational resource as we approach the municipal election on April 10, 2021.

This project is not affiliated with the town government of Arlington in any way. While some of our data was sourced from publicly available data on the town government website (see below), this project and our approach to its presentation are purely our own.

## Meet The Team

### Dylan Phelan

Dylan Phelan is a full-time software engineer at The MITRE Corporation and a part-time Master’s student at Tufts University. His work ranges from web development and ETL projects in Healthcare IT, to researching the operationalization of Ethics in Software Engineering and the impact of different electoral systems on minority representation. Dylan has been an Arlington resident for 5 years and lives in Precinct 9.

### Graham Goudeau

Graham Goudeau is currently a full-time software engineer at chewy.com. He is primarily interested in backend development in distributed microservice topologies, with a special focus on cloud-native technologies like service meshes. He has also worked on performance-critical auction logic and site reliability for high-traffic web applications. Graham is an Arlington resident and lives in Precinct 11.

### Matt Gramigna


## FAQ

### How Can I Contact The Team?

All questions, comments, and feedback can be directed to contact@votesmartarlington.com.

### Where Does This Data Come From?

This data is combined in a novel way from two sources:

1. Public voting records on the Arlington town government website: https://www.arlingtonma.gov/town-governance/town-meeting/2020-town-meeting
2. Data (licensed under Creative Commons) available here: https://menotomymatters.com/

Menotomy Matters's data was accessed directly from the raw sources on GitHub: https://github.com/ShaneCurcuru/menotomymatters

Manual processing was done using small scripts available in our code. See another FAQ for where to find our code.

### Where Can I See The Code Running This Website?

Our code and data is available under a copyleft license on GitHub: https://github.com/Dtphelan1/arlington-ma-town-member-voting

### How Is This Data Licensed?

Our data is available under a copyleft license. See our GitHub repository for more detailed information.

### Where Can I Find More Information About The April 10 Election?

Find information about Arlington town governance, including elections, here: https://www.arlingtonma.gov/town-governance/elections-voting 

### Where Can I Find Arlington Town Resources?

**Comment by Dtphelan1** [comment]
Great job Graham 10/10
